<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/cities.proto

namespace GPBMetadata\Proto;

class Cities
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
t
proto/cities.protocities"%
City
name (	
country (	B\'Z%github.com/camilovietnam/proto/citiesbproto3'
        , true);

        static::$is_initialized = true;
    }
}

